/**
 * setupRoutes — lightweight HTTP routes for the onboarding flow.
 *
 * GET  /api/setup/git-status        — checks if git is installed and configured
 * GET  /api/setup/import/scan       — scans provider history directories for detected projects
 * POST /api/setup/import/execute    — creates Bird Code projects + thread stubs from a selection
 */
import { exec } from "node:child_process";
import type { Dirent } from "node:fs";
import * as nodeFs from "node:fs/promises";
import * as os from "node:os";
import * as nodePath from "node:path";
import { promisify } from "node:util";
import { Effect, Layer, Option } from "effect";
import { HttpRouter, HttpServerRequest, HttpServerResponse } from "effect/unstable/http";
import {
  CommandId,
  DEFAULT_PROVIDER_INTERACTION_MODE,
  DEFAULT_RUNTIME_MODE,
  ImportRequest,
  ProjectId,
  TrimmedNonEmptyString,
  ThreadId,
  type OrchestrationCommand,
} from "@t3tools/contracts";
import { ServerConfig } from "./config";
import { authorizeServerHttpRequest } from "./http";
import { OrchestrationEngineService } from "./orchestration/Services/OrchestrationEngine";

const execAsync = promisify(exec);
const SETUP_CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "content-type",
} as const;

// ── Provider history roots ───────────────────────────────────────────────────

/** Known candidate paths for each provider's conversation history. */
const PROVIDER_HISTORY_CANDIDATES: Record<string, (home: string) => string[]> = {
  codex: (home) => [
    ...(process.env["CODEX_HOME"] ? [process.env["CODEX_HOME"]] : []),
    nodePath.join(home, ".codex", "sessions"),
    nodePath.join(home, ".codex"),
  ],
  claudeAgent: (home) => [
    nodePath.join(home, ".claude", "projects"),
    nodePath.join(home, ".claude"),
  ],
  gemini: (home) => [nodePath.join(home, ".gemini", "sessions"), nodePath.join(home, ".gemini")],
  opencode: (home) => [
    nodePath.join(home, ".config", "opencode"),
    nodePath.join(home, ".opencode"),
  ],
};

async function resolveProviderHistoryRoot(provider: string): Promise<string | null> {
  const home = os.homedir();
  const candidates = (PROVIDER_HISTORY_CANDIDATES[provider]?.(home) ?? []).filter(Boolean);
  for (const candidate of candidates) {
    try {
      await nodeFs.access(candidate);
      return candidate;
    } catch {
      // Not accessible — try next candidate
    }
  }
  return null;
}

// ── JSONL parsing helpers ────────────────────────────────────────────────────

/**
 * Read the first N lines from a file's head without loading the entire file.
 * The last line is dropped if the read buffer was filled (likely truncated mid-line).
 */
async function readFileHeadLines(
  filePath: string,
  maxLines = 80,
  maxBytes = 256 * 1024,
): Promise<string[]> {
  let fh: nodeFs.FileHandle | null = null;
  try {
    fh = await nodeFs.open(filePath, "r");
    const buf = Buffer.allocUnsafe(maxBytes);
    const { bytesRead } = await fh.read(buf, 0, maxBytes, 0);
    if (bytesRead === 0) return [];
    const text = buf.subarray(0, bytesRead).toString("utf8");
    const lines = text.split("\n");
    if (bytesRead === maxBytes) lines.pop();
    return lines.slice(0, maxLines).filter((l) => l.length > 0);
  } catch {
    return [];
  } finally {
    if (fh) await fh.close().catch(() => undefined);
  }
}

function tryParseJson(s: string): unknown {
  try {
    return JSON.parse(s);
  } catch {
    return null;
  }
}

/**
 * Claude Code encodes workspace paths as directory names by replacing '/' with '-'.
 * This is lossy for paths containing dashes, so we only use this as a fallback — the
 * canonical `cwd` from inside the JSONL is preferred.
 */
function decodeClaudeProjectDir(name: string): string {
  return "/" + name.replace(/^-/, "").replace(/-/g, "/");
}

/** Prefixes that identify wrapper/boilerplate messages which shouldn't be used as a thread title. */
const BOILERPLATE_PREFIXES = [
  "<environment_context>",
  "# Context from my IDE setup",
  "<system-reminder>",
  "<command-message>",
  "<command-name>",
  "<local-command-caveat>",
  "<local-command-stdout>",
  "<local-command-stderr>",
  "Caveat: The messages below were generated by",
  "# AGENTS.md instructions for",
  "# CLAUDE.md instructions for",
  "# GEMINI.md instructions for",
  "# PROJECT.md",
];

function isBoilerplateUserText(text: string): boolean {
  const t = text.trimStart();
  return BOILERPLATE_PREFIXES.some((p) => t.startsWith(p));
}

function normalizeTitle(text: string): string {
  return text.trim().replace(/\s+/g, " ").slice(0, 80);
}

type DiscoveredSession = {
  /** Absolute workspace path the session was started in (authoritative from JSONL). */
  projectCwd: string;
  /** Provider's own session identifier (UUID). */
  sessionId: string;
  /** Absolute file path to the .jsonl rollout. */
  filePath: string;
  /** First non-boilerplate user message, normalized to ≤80 chars. Null if nothing usable. */
  title: string | null;
  /** File mtime for sorting. */
  modifiedAtMs: number;
};

// ── Claude Code discovery ────────────────────────────────────────────────────

function extractClaudeUserText(content: unknown): string | null {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    for (const block of content) {
      if (block && typeof block === "object" && "type" in block) {
        const b = block as { type: string; text?: unknown };
        if (b.type === "text" && typeof b.text === "string") return b.text;
      }
    }
  }
  return null;
}

async function readClaudeSessionMeta(
  filePath: string,
  encodedProjectDir: string,
): Promise<DiscoveredSession | null> {
  const lines = await readFileHeadLines(filePath);
  if (lines.length === 0) return null;

  let cwd: string | null = null;
  let sessionId: string | null = null;
  let title: string | null = null;

  for (const line of lines) {
    const obj = tryParseJson(line) as {
      cwd?: unknown;
      sessionId?: unknown;
      type?: unknown;
      message?: { role?: unknown; content?: unknown };
    } | null;
    if (!obj) continue;

    if (cwd === null && typeof obj.cwd === "string") cwd = obj.cwd;
    if (sessionId === null && typeof obj.sessionId === "string") sessionId = obj.sessionId;

    if (title === null && obj.type === "user" && obj.message?.role === "user") {
      const text = extractClaudeUserText(obj.message.content);
      if (text && !isBoilerplateUserText(text)) {
        const normalized = normalizeTitle(text);
        if (normalized.length > 0) title = normalized;
      }
    }

    if (cwd && sessionId && title) break;
  }

  let mtimeMs = 0;
  try {
    const stat = await nodeFs.stat(filePath);
    mtimeMs = stat.mtimeMs;
  } catch {
    return null;
  }

  return {
    projectCwd: cwd ?? decodeClaudeProjectDir(encodedProjectDir),
    sessionId: sessionId ?? nodePath.basename(filePath, ".jsonl"),
    filePath,
    title,
    modifiedAtMs: mtimeMs,
  };
}

async function discoverClaudeSessions(root: string): Promise<DiscoveredSession[]> {
  const out: DiscoveredSession[] = [];
  let topEntries: Dirent[];
  try {
    topEntries = await nodeFs.readdir(root, { withFileTypes: true });
  } catch {
    return out;
  }

  for (const dirent of topEntries) {
    if (!dirent.isDirectory()) continue;
    const projectDir = nodePath.join(root, dirent.name);
    let inner: string[];
    try {
      inner = await nodeFs.readdir(projectDir);
    } catch {
      continue;
    }
    for (const fname of inner) {
      if (!fname.endsWith(".jsonl")) continue;
      const filePath = nodePath.join(projectDir, fname);
      const session = await readClaudeSessionMeta(filePath, dirent.name);
      if (session) out.push(session);
    }
  }
  return out;
}

// ── Codex discovery ──────────────────────────────────────────────────────────

function extractCodexUserText(content: unknown): string | null {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    for (const block of content) {
      if (block && typeof block === "object" && "text" in block) {
        const b = block as { text?: unknown };
        if (typeof b.text === "string") return b.text;
      }
    }
  }
  return null;
}

async function readCodexSessionMeta(filePath: string): Promise<DiscoveredSession | null> {
  const lines = await readFileHeadLines(filePath);
  if (lines.length === 0) return null;

  let cwd: string | null = null;
  let sessionId: string | null = null;
  let title: string | null = null;

  for (const line of lines) {
    const obj = tryParseJson(line) as { type?: unknown; payload?: unknown } | null;
    if (!obj || !obj.payload || typeof obj.payload !== "object") continue;
    const payload = obj.payload as {
      id?: unknown;
      cwd?: unknown;
      type?: unknown;
      role?: unknown;
      content?: unknown;
    };

    if (obj.type === "session_meta") {
      if (cwd === null && typeof payload.cwd === "string") cwd = payload.cwd;
      if (sessionId === null && typeof payload.id === "string") sessionId = payload.id;
    }

    if (
      title === null &&
      obj.type === "response_item" &&
      payload.type === "message" &&
      payload.role === "user"
    ) {
      const text = extractCodexUserText(payload.content);
      if (text && !isBoilerplateUserText(text)) {
        const normalized = normalizeTitle(text);
        if (normalized.length > 0) title = normalized;
      }
    }

    if (cwd && sessionId && title) break;
  }

  if (!cwd) return null; // Can't group without a workspace path

  let mtimeMs = 0;
  try {
    const stat = await nodeFs.stat(filePath);
    mtimeMs = stat.mtimeMs;
  } catch {
    return null;
  }

  return {
    projectCwd: cwd,
    sessionId: sessionId ?? nodePath.basename(filePath, ".jsonl"),
    filePath,
    title,
    modifiedAtMs: mtimeMs,
  };
}

async function walkCodexDir(dir: string, out: DiscoveredSession[], depth: number): Promise<void> {
  if (depth > 5) return;
  let entries: Dirent[];
  try {
    entries = await nodeFs.readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const p = nodePath.join(dir, entry.name);
    if (entry.isDirectory()) {
      await walkCodexDir(p, out, depth + 1);
    } else if (
      entry.isFile() &&
      entry.name.startsWith("rollout-") &&
      entry.name.endsWith(".jsonl")
    ) {
      const session = await readCodexSessionMeta(p);
      if (session) out.push(session);
    }
  }
}

async function discoverCodexSessions(root: string): Promise<DiscoveredSession[]> {
  const out: DiscoveredSession[] = [];
  await walkCodexDir(root, out, 0);
  return out;
}

// ── Generic fallback discovery (Gemini / OpenCode) ───────────────────────────

/**
 * Flat-directory scan used for providers we haven't implemented smart discovery for.
 * Groups conversation files by immediate subdirectory, same as the pre-existing behaviour
 * but now accepts `.jsonl` in addition to `.json` / `.md`.
 */
async function scanProviderHistoryGeneric(
  historyRoot: string,
): Promise<
  Array<{ projectName: string; projectPath: string; historyPath: string; threadCount: number }>
> {
  const results: Array<{
    projectName: string;
    projectPath: string;
    historyPath: string;
    threadCount: number;
  }> = [];
  try {
    const entries = await nodeFs.readdir(historyRoot, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const historyPath = nodePath.join(historyRoot, entry.name);
      let threadCount = 0;
      try {
        const inner = await nodeFs.readdir(historyPath);
        threadCount = inner.filter(
          (f) => f.endsWith(".json") || f.endsWith(".jsonl") || f.endsWith(".md"),
        ).length;
      } catch {
        // Unreadable inner dir — count stays 0
      }
      if (threadCount === 0) continue;
      results.push({
        projectName: entry.name,
        projectPath: historyPath,
        historyPath,
        threadCount,
      });
    }
  } catch {
    // Root dir unreadable — return empty
  }
  return results;
}

// ── Aggregation ──────────────────────────────────────────────────────────────

type ScannedProject = {
  provider: string;
  projectName: string;
  projectPath: string;
  historyPath: string;
  threadCount: number;
};

function groupSessionsByCwd(
  provider: string,
  historyRoot: string,
  sessions: DiscoveredSession[],
): ScannedProject[] {
  const byCwd = new Map<string, DiscoveredSession[]>();
  for (const s of sessions) {
    const arr = byCwd.get(s.projectCwd) ?? [];
    arr.push(s);
    byCwd.set(s.projectCwd, arr);
  }
  return Array.from(byCwd.entries()).map(([cwd, list]) => ({
    provider,
    projectName: nodePath.basename(cwd) || cwd,
    projectPath: cwd,
    historyPath: historyRoot,
    threadCount: list.length,
  }));
}

async function scanAllProviders(): Promise<ScannedProject[]> {
  const out: ScannedProject[] = [];

  // Smart providers: parse JSONL and group by actual workspace cwd.
  for (const provider of ["codex", "claudeAgent"] as const) {
    const root = await resolveProviderHistoryRoot(provider);
    if (!root) continue;
    const sessions =
      provider === "codex" ? await discoverCodexSessions(root) : await discoverClaudeSessions(root);
    out.push(...groupSessionsByCwd(provider, root, sessions));
  }

  // Generic providers: flat directory scan.
  for (const provider of ["gemini", "opencode"] as const) {
    const root = await resolveProviderHistoryRoot(provider);
    if (!root) continue;
    const projects = await scanProviderHistoryGeneric(root);
    for (const project of projects) {
      out.push({ provider, ...project });
    }
  }

  return out;
}

/**
 * Re-discovers sessions for a single selection at import time so we can use real
 * first-user-message titles rather than UUID filenames.
 */
async function enumerateSessionsForSelection(
  provider: string,
  historyPath: string,
  projectCwd: string,
): Promise<DiscoveredSession[]> {
  if (provider === "claudeAgent") {
    const all = await discoverClaudeSessions(historyPath);
    return all.filter((s) => s.projectCwd === projectCwd);
  }
  if (provider === "codex") {
    const all = await discoverCodexSessions(historyPath);
    return all.filter((s) => s.projectCwd === projectCwd);
  }
  return [];
}

// ── Auth helper ───────────────────────────────────────────────────────────────

/**
 * Setup routes touch the local filesystem (provider history, project paths)
 * and create projects in the orchestration engine. Without this guard, a
 * malicious page on localhost or any LAN device on a tunneled web-mode
 * deployment can create projects pointing at any path on disk and then act
 * on them via the rest of the WS RPC surface.
 *
 * Yields an unauthorized response when the configured auth token is missing
 * or invalid; resolves to `null` to allow the handler to proceed.
 */
const authorizeSetupRequest = Effect.gen(function* () {
  const request = yield* HttpServerRequest.HttpServerRequest;
  const config = yield* ServerConfig;
  const denied = authorizeServerHttpRequest(request, config);
  if (denied !== null) {
    return Option.some(HttpServerResponse.setHeaders(denied, SETUP_CORS_HEADERS));
  }
  return Option.none<HttpServerResponse.HttpServerResponse>();
});

// ── Git Status Route ──────────────────────────────────────────────────────────

export const gitStatusRouteLayer = HttpRouter.add(
  "GET",
  "/api/setup/git-status",
  Effect.gen(function* () {
    const denied = yield* authorizeSetupRequest;
    if (Option.isSome(denied)) return denied.value;
    const version = yield* Effect.tryPromise(() =>
      execAsync("git --version")
        .then((r) => r.stdout.trim())
        .catch(() => null),
    ).pipe(Effect.orElseSucceed(() => null));

    const [name, email] = yield* Effect.tryPromise(() =>
      Promise.all([
        execAsync("git config --global user.name")
          .then((r) => r.stdout.trim() || null)
          .catch(() => null),
        execAsync("git config --global user.email")
          .then((r) => r.stdout.trim() || null)
          .catch(() => null),
      ]),
    ).pipe(Effect.orElseSucceed(() => [null, null] as const));

    return HttpServerResponse.setHeaders(
      HttpServerResponse.jsonUnsafe({
        installed: version !== null,
        version: version ?? null,
        nameConfigured: typeof name === "string" && name.length > 0,
        emailConfigured: typeof email === "string" && email.length > 0,
        name: name ?? null,
        email: email ?? null,
      }),
      SETUP_CORS_HEADERS,
    );
  }),
);

// ── Import Scan Route ─────────────────────────────────────────────────────────

export const importScanRouteLayer = HttpRouter.add(
  "GET",
  "/api/setup/import/scan",
  Effect.gen(function* () {
    const denied = yield* authorizeSetupRequest;
    if (Option.isSome(denied)) return denied.value;
    const projects = yield* Effect.tryPromise(() => scanAllProviders()).pipe(
      Effect.orElseSucceed(() => [] as ScannedProject[]),
    );

    return HttpServerResponse.setHeaders(
      HttpServerResponse.jsonUnsafe({ projects }),
      SETUP_CORS_HEADERS,
    );
  }),
);

export const setupOptionsRouteLayer = HttpRouter.add(
  "OPTIONS",
  "/api/setup/*",
  Effect.succeed(HttpServerResponse.empty({ status: 204, headers: SETUP_CORS_HEADERS })),
);

// ── Import Execute Route ──────────────────────────────────────────────────────

/**
 * Wraps in Layer.unwrap so OrchestrationEngineService is available via
 * closure inside the route handler.
 *
 * NOTE: We intentionally bypass normalizeDispatchCommand here. That helper
 * needs WorkspacePaths / FileSystem / ServerConfig which are not provided in
 * this layer's context. For the import flow the workspaceRoot is a resolved,
 * already-validated path from PROVIDER_HISTORY_CANDIDATES so normalisation
 * is not required.
 */
export const importExecuteRouteLayer = Layer.unwrap(
  Effect.gen(function* () {
    const engineOption = yield* Effect.serviceOption(OrchestrationEngineService);

    // Build the set of allowed history roots once so we can validate each
    // request's historyPath against it (defence-in-depth on a local server).
    const home = os.homedir();
    const allowedRoots = new Set<string>(
      Object.values(PROVIDER_HISTORY_CANDIDATES).flatMap((fn) => fn(home).filter(Boolean)),
    );

    const isAllowedPath = (p: string) => {
      for (const root of allowedRoots) {
        if (p === root || p.startsWith(root + nodePath.sep)) return true;
      }
      return false;
    };

    return HttpRouter.add(
      "POST",
      "/api/setup/import/execute",
      Effect.gen(function* () {
        const denied = yield* authorizeSetupRequest;
        if (Option.isSome(denied)) return denied.value;
        if (Option.isNone(engineOption)) {
          return HttpServerResponse.setHeaders(
            HttpServerResponse.jsonUnsafe(
              { error: "Orchestration engine unavailable" },
              { status: 503 },
            ),
            SETUP_CORS_HEADERS,
          );
        }
        const engine = engineOption.value;
        // Parse request body — return 400 explicitly instead of silently
        // returning an empty selection list, so callers see why their request failed.
        const bodyResult = yield* HttpServerRequest.schemaBodyJson(ImportRequest).pipe(
          Effect.result,
        );
        if (bodyResult._tag === "Failure") {
          return HttpServerResponse.setHeaders(
            HttpServerResponse.jsonUnsafe(
              { error: "Invalid request body", detail: String(bodyResult.failure) },
              { status: 400 },
            ),
            SETUP_CORS_HEADERS,
          );
        }
        const body = bodyResult.success;

        let importedProjectCount = 0;
        let importedThreadCount = 0;
        const errors: string[] = [];

        for (const selection of body.selections) {
          // Security: only read from paths within known provider history roots
          if (!isAllowedPath(selection.historyPath)) {
            errors.push(`Skipped "${selection.projectName}": path not within an allowed root.`);
            continue;
          }

          // Validate projectPath: must be absolute, fully resolved (no `..`),
          // not point at root or a system directory. Without this the server
          // would accept e.g. "/", "/etc", or arbitrary paths supplied by a
          // local attacker and create a project bound to that workspace.
          const rawProjectPath = selection.projectPath;
          const resolvedProjectPath = nodePath.resolve(rawProjectPath);
          const isAbsolute = nodePath.isAbsolute(rawProjectPath);
          const isNormalized = rawProjectPath === resolvedProjectPath;
          const isSensitiveRoot =
            resolvedProjectPath === "/" ||
            resolvedProjectPath === "/etc" ||
            resolvedProjectPath === "/usr" ||
            resolvedProjectPath === "/bin" ||
            resolvedProjectPath === "/sbin" ||
            resolvedProjectPath === "/var" ||
            resolvedProjectPath === os.homedir();
          if (!isAbsolute || !isNormalized || isSensitiveRoot) {
            errors.push(
              `Skipped "${selection.projectName}": invalid project path "${rawProjectPath}".`,
            );
            continue;
          }
          const projectPathStat = yield* Effect.tryPromise(() =>
            nodeFs.stat(resolvedProjectPath),
          ).pipe(Effect.result);
          if (projectPathStat._tag === "Failure" || !projectPathStat.success.isDirectory()) {
            errors.push(`Skipped "${selection.projectName}": project path is not a directory.`);
            continue;
          }

          const createdAt = new Date().toISOString();
          const title = TrimmedNonEmptyString.makeUnsafe(
            selection.projectName.slice(0, 200) || "Imported Project",
          );
          const workspaceRoot = TrimmedNonEmptyString.makeUnsafe(resolvedProjectPath);

          // C6: dedupe project by workspaceRoot. Re-running import previously
          // generated fresh UUIDs every time, doubling the sidebar on every
          // run. Look up an existing non-deleted project first and reuse it.
          const readModelBeforeProject = yield* engine.getReadModel();
          const existingProject = readModelBeforeProject.projects.find(
            (entry) => entry.workspaceRoot === resolvedProjectPath && entry.deletedAt === null,
          );

          let projectId: ProjectId;
          if (existingProject) {
            projectId = existingProject.id;
            // No project.create dispatch — already exists.
          } else {
            projectId = ProjectId.makeUnsafe(crypto.randomUUID());
            const projectCommand: OrchestrationCommand = {
              type: "project.create",
              commandId: CommandId.makeUnsafe(`import:project:${crypto.randomUUID()}`),
              projectId,
              title,
              workspaceRoot,
              createdAt,
            };

            const projectResult = yield* engine.dispatch(projectCommand).pipe(
              Effect.catch((err) => {
                errors.push(`Dispatch project "${selection.projectName}": ${String(err)}`);
                return Effect.succeed({ sequence: -1 });
              }),
            );
            if (projectResult.sequence === -1) {
              continue;
            }
            importedProjectCount++;
          }

          // C6: pre-load existing thread titles for this project so we can
          // skip imports that would duplicate. Imperfect — import payloads
          // don't carry a stable (provider, sessionId) identity in the read
          // model — but title-based dedupe blocks the disaster case where a
          // re-run doubles every imported thread.
          const readModelAfterProject = yield* engine.getReadModel();
          const existingTitlesForProject = new Set(
            readModelAfterProject.threads
              .filter((entry) => entry.projectId === projectId && entry.deletedAt === null)
              .map((entry) => entry.title.trim().toLowerCase()),
          );

          // ── Discover threads for this project ─────────────────────────────
          // For smart providers (codex, claudeAgent) this returns real sessions
          // with parsed titles. For generic providers it falls back to a flat
          // directory listing where filenames become titles.
          const sessions = yield* Effect.tryPromise(() =>
            enumerateSessionsForSelection(
              selection.provider,
              selection.historyPath,
              selection.projectPath,
            ),
          ).pipe(Effect.orElseSucceed(() => [] as DiscoveredSession[]));

          type ThreadToCreate = { title: string };
          const threadsToCreate: ThreadToCreate[] = [];

          if (sessions.length > 0) {
            // Sort newest-first so the most recent CLI conversations appear at the top.
            sessions.sort((a, b) => b.modifiedAtMs - a.modifiedAtMs);
            for (const session of sessions.slice(0, 100)) {
              const rawTitle = session.title ?? session.sessionId;
              threadsToCreate.push({
                title: rawTitle.slice(0, 80).trim() || "Imported conversation",
              });
            }
          } else {
            // Generic-provider fallback: enumerate files directly.
            const files = yield* Effect.tryPromise(() =>
              nodeFs
                .readdir(selection.historyPath)
                .then((entries) =>
                  entries
                    .filter((f) => f.endsWith(".json") || f.endsWith(".jsonl") || f.endsWith(".md"))
                    .slice(0, 50),
                ),
            ).pipe(Effect.orElseSucceed(() => [] as string[]));

            const fallback =
              files.length > 0
                ? files
                : [`${selection.projectName} (imported)`.slice(0, 80).trim()];

            for (const file of fallback) {
              const rawTitle =
                file
                  .replace(/\.(json|jsonl|md)$/, "")
                  .replace(/[_-]/g, " ")
                  .trim()
                  .slice(0, 80) || "Imported conversation";
              threadsToCreate.push({ title: rawTitle });
            }
          }

          for (const { title: rawTitle } of threadsToCreate) {
            // C6: skip threads whose title already exists for this project
            // (case-insensitive, trimmed) — prevents re-imports from doubling.
            const titleKey = rawTitle.trim().toLowerCase();
            if (existingTitlesForProject.has(titleKey)) {
              continue;
            }

            const threadId = ThreadId.makeUnsafe(crypto.randomUUID());
            const threadTitle = TrimmedNonEmptyString.makeUnsafe(rawTitle);

            const threadCommand: OrchestrationCommand = {
              type: "thread.create",
              commandId: CommandId.makeUnsafe(`import:thread:${crypto.randomUUID()}`),
              threadId,
              projectId,
              title: threadTitle,
              // manifest = smart-router: routes to cheapest capable model automatically
              modelSelection: {
                provider: "manifest",
                model: TrimmedNonEmptyString.makeUnsafe("auto"),
              },
              runtimeMode: DEFAULT_RUNTIME_MODE,
              interactionMode: DEFAULT_PROVIDER_INTERACTION_MODE,
              branch: null,
              worktreePath: null,
              createdAt,
            };

            const threadResult = yield* engine.dispatch(threadCommand).pipe(
              Effect.catch((err) => {
                errors.push(`Dispatch thread "${rawTitle}": ${String(err)}`);
                return Effect.succeed({ sequence: -1 });
              }),
            );
            if (threadResult.sequence !== -1) {
              importedThreadCount++;
              existingTitlesForProject.add(titleKey);
            }
          }
        }

        return HttpServerResponse.setHeaders(
          HttpServerResponse.jsonUnsafe({
            importedProjectCount,
            importedThreadCount,
            errors,
          }),
          SETUP_CORS_HEADERS,
        );
      }),
    );
  }),
);
