/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as TerminalPopoutThreadIdRouteImport } from './routes/terminal-popout.$threadId'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsPersonalizationRouteImport } from './routes/settings.personalization'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsMobileRouteImport } from './routes/settings.mobile'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as SettingsGitRouteImport } from './routes/settings.git'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as PopoutThreadIdRouteImport } from './routes/popout.$threadId'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const TerminalPopoutThreadIdRoute = TerminalPopoutThreadIdRouteImport.update({
  id: '/terminal-popout/$threadId',
  path: '/terminal-popout/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalizationRoute = SettingsPersonalizationRouteImport.update({
  id: '/personalization',
  path: '/personalization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMobileRoute = SettingsMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGitRoute = SettingsGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const PopoutThreadIdRoute = PopoutThreadIdRouteImport.update({
  id: '/popout/$threadId',
  path: '/popout/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/automations': typeof AutomationsRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/popout/$threadId': typeof PopoutThreadIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/mobile': typeof SettingsMobileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/terminal-popout/$threadId': typeof TerminalPopoutThreadIdRoute
}
export interface FileRoutesByTo {
  '/automations': typeof AutomationsRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/popout/$threadId': typeof PopoutThreadIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/mobile': typeof SettingsMobileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/terminal-popout/$threadId': typeof TerminalPopoutThreadIdRoute
  '/': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/automations': typeof AutomationsRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/popout/$threadId': typeof PopoutThreadIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/mobile': typeof SettingsMobileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/terminal-popout/$threadId': typeof TerminalPopoutThreadIdRoute
  '/_chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/$threadId'
    | '/popout/$threadId'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/git'
    | '/settings/mcp'
    | '/settings/mobile'
    | '/settings/notifications'
    | '/settings/personalization'
    | '/settings/providers'
    | '/terminal-popout/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/automations'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/$threadId'
    | '/popout/$threadId'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/git'
    | '/settings/mcp'
    | '/settings/mobile'
    | '/settings/notifications'
    | '/settings/personalization'
    | '/settings/providers'
    | '/terminal-popout/$threadId'
    | '/'
  id:
    | '__root__'
    | '/_chat'
    | '/automations'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/_chat/$threadId'
    | '/popout/$threadId'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/git'
    | '/settings/mcp'
    | '/settings/mobile'
    | '/settings/notifications'
    | '/settings/personalization'
    | '/settings/providers'
    | '/terminal-popout/$threadId'
    | '/_chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AutomationsRoute: typeof AutomationsRoute
  PluginsRoute: typeof PluginsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  PopoutThreadIdRoute: typeof PopoutThreadIdRoute
  TerminalPopoutThreadIdRoute: typeof TerminalPopoutThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/terminal-popout/$threadId': {
      id: '/terminal-popout/$threadId'
      path: '/terminal-popout/$threadId'
      fullPath: '/terminal-popout/$threadId'
      preLoaderRoute: typeof TerminalPopoutThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personalization': {
      id: '/settings/personalization'
      path: '/personalization'
      fullPath: '/settings/personalization'
      preLoaderRoute: typeof SettingsPersonalizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mobile': {
      id: '/settings/mobile'
      path: '/mobile'
      fullPath: '/settings/mobile'
      preLoaderRoute: typeof SettingsMobileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/git': {
      id: '/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof SettingsGitRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/popout/$threadId': {
      id: '/popout/$threadId'
      path: '/popout/$threadId'
      fullPath: '/popout/$threadId'
      preLoaderRoute: typeof PopoutThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsGitRoute: typeof SettingsGitRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsMobileRoute: typeof SettingsMobileRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPersonalizationRoute: typeof SettingsPersonalizationRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsGitRoute: SettingsGitRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsMobileRoute: SettingsMobileRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPersonalizationRoute: SettingsPersonalizationRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AutomationsRoute: AutomationsRoute,
  PluginsRoute: PluginsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  PopoutThreadIdRoute: PopoutThreadIdRoute,
  TerminalPopoutThreadIdRoute: TerminalPopoutThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
